language: java

matrix:
  include:
    - os: osx
    - os: linux
      jdk: openjdk7
    - os: linux
      jdk: oraclejdk8

sudo: true

install:
    - cp -rf ~/.m2/org/eclipse/tycho/* ~/.m2/org/eclipse/jdt/
    - "./.travis_install.sh"
script: "./.travis_run_tests.sh"

cache:
  directories:
    - $HOME/.m2
